stages:
  - build
  - deploy

build-frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}/frontend:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH



deploy-frontend:
  stage: deploy
  image: curlimages/curl
  script:
    - curl -X POST ${PORTAINER_SERVICE_URL_FRONTEND}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH



build-frontend-dev:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/frontend"
      --dockerfile "${CI_PROJECT_DIR}/frontend/Dockerfile"
      --destination "${DOCKER_IMAGE_NAME}"
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH


